title: Steve Kim
description: My Personal Blog
author: Steve Kim
logo: /blockchain/static/img/avatar.png
github: https://github.com/softkid
about: Freelance developer

baseurl: "https://softkid.github.io/blockchain"
url: "https://softkid.github.io/blockchain"

allowsearch: true

disqus_shortname: aboutashu
google_analytics: UA-72862926-1

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
