title: Steve Kim
description: BlockChain Blog
author: Steve Kim
logo: /static/img/avatar.png
github: https://github.com/softkid
about: Developer, Marketing

baseurl: "https://softkid.github.io"
url: "https://softkid.github.io"

allowsearch: true

disqus_shortname: softkids
google_analytics: UA-51091735-2

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
